// Generated by `pnpm db:types` from the Supabase schema. Do not edit by hand.
// eslint-disable

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "action_executions": {
                  Row: {
                    "action_type": string,"attempt": number,"created_at": string,"error": string | null,"executed_by": string,"external_refs": NonNullable<Json>,"finished_at": string | null,"id": string,"idempotency_key": string,"irreversible": boolean,"params": NonNullable<Json>,"proposal_id": string | null,"proposed_action_id": string | null,"result": Json | null,"scheduled_for": string | null,"started_at": string | null,"status": string,"ticket_id": string,"updated_at": string
                  }
                  Insert: {
                    "action_type": string,"attempt"?: number,"created_at"?: string,"error"?: string | null,"executed_by": string,"external_refs"?: NonNullable<Json>,"finished_at"?: string | null,"id"?: string,"idempotency_key": string,"irreversible"?: boolean,"params"?: NonNullable<Json>,"proposal_id"?: string | null,"proposed_action_id"?: string | null,"result"?: Json | null,"scheduled_for"?: string | null,"started_at"?: string | null,"status"?: string,"ticket_id": string,"updated_at"?: string
                  }
                  Update: {
                    "action_type"?: string,"attempt"?: number,"created_at"?: string,"error"?: string | null,"executed_by"?: string,"external_refs"?: NonNullable<Json>,"finished_at"?: string | null,"id"?: string,"idempotency_key"?: string,"irreversible"?: boolean,"params"?: NonNullable<Json>,"proposal_id"?: string | null,"proposed_action_id"?: string | null,"result"?: Json | null,"scheduled_for"?: string | null,"started_at"?: string | null,"status"?: string,"ticket_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "action_executions_proposal_id_fkey"
      columns: ["proposal_id"]
isOneToOne: false
      referencedRelation: "proposals"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "action_executions_proposed_action_id_fkey"
      columns: ["proposed_action_id"]
isOneToOne: false
      referencedRelation: "proposed_actions"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "action_executions_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"action_locks": {
                  Row: {
                    "action_type": string,"app_id": string,"changed_at": string,"locked": boolean
                  }
                  Insert: {
                    "action_type": string,"app_id": string,"changed_at"?: string,"locked"?: boolean
                  }
                  Update: {
                    "action_type"?: string,"app_id"?: string,"changed_at"?: string,"locked"?: boolean
                  }
                  Relationships: [
                    {
      foreignKeyName: "action_locks_app_id_fkey"
      columns: ["app_id"]
isOneToOne: false
      referencedRelation: "apps"
      referencedColumns: ["id"]
    }
                  ]
                },"agent_runs": {
                  Row: {
                    "attempt": number,"cache_creation_tokens": number | null,"cache_read_tokens": number | null,"cost_usd": number | null,"created_at": string,"duration_ms": number | null,"error": string | null,"finished_at": string | null,"id": string,"input_tokens": number | null,"job_id": string | null,"model": string | null,"output_tokens": number | null,"progress": NonNullable<Json>,"proposal_id": string | null,"started_at": string | null,"status": string,"ticket_id": string,"trigger": string
                  }
                  Insert: {
                    "attempt"?: number,"cache_creation_tokens"?: number | null,"cache_read_tokens"?: number | null,"cost_usd"?: number | null,"created_at"?: string,"duration_ms"?: number | null,"error"?: string | null,"finished_at"?: string | null,"id"?: string,"input_tokens"?: number | null,"job_id"?: string | null,"model"?: string | null,"output_tokens"?: number | null,"progress"?: NonNullable<Json>,"proposal_id"?: string | null,"started_at"?: string | null,"status"?: string,"ticket_id": string,"trigger": string
                  }
                  Update: {
                    "attempt"?: number,"cache_creation_tokens"?: number | null,"cache_read_tokens"?: number | null,"cost_usd"?: number | null,"created_at"?: string,"duration_ms"?: number | null,"error"?: string | null,"finished_at"?: string | null,"id"?: string,"input_tokens"?: number | null,"job_id"?: string | null,"model"?: string | null,"output_tokens"?: number | null,"progress"?: NonNullable<Json>,"proposal_id"?: string | null,"started_at"?: string | null,"status"?: string,"ticket_id"?: string,"trigger"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "agent_runs_proposal_id_fkey"
      columns: ["proposal_id"]
isOneToOne: false
      referencedRelation: "proposals"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "agent_runs_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"agent_tool_calls": {
                  Row: {
                    "context_measured": boolean,"context_tokens": number | null,"created_at": string,"duration_ms": number | null,"id": string,"input": NonNullable<Json>,"model_call_id": string | null,"ok": boolean,"result_chars": number,"run_id": string | null,"source": string | null,"ticket_id": string | null,"tool": string,"turn": number
                  }
                  Insert: {
                    "context_measured"?: boolean,"context_tokens"?: number | null,"created_at"?: string,"duration_ms"?: number | null,"id"?: string,"input"?: NonNullable<Json>,"model_call_id"?: string | null,"ok"?: boolean,"result_chars"?: number,"run_id"?: string | null,"source"?: string | null,"ticket_id"?: string | null,"tool": string,"turn": number
                  }
                  Update: {
                    "context_measured"?: boolean,"context_tokens"?: number | null,"created_at"?: string,"duration_ms"?: number | null,"id"?: string,"input"?: NonNullable<Json>,"model_call_id"?: string | null,"ok"?: boolean,"result_chars"?: number,"run_id"?: string | null,"source"?: string | null,"ticket_id"?: string | null,"tool"?: string,"turn"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "agent_tool_calls_model_call_id_fkey"
      columns: ["model_call_id"]
isOneToOne: false
      referencedRelation: "model_calls"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "agent_tool_calls_run_id_fkey"
      columns: ["run_id"]
isOneToOne: false
      referencedRelation: "agent_runs"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "agent_tool_calls_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"allowed_users": {
                  Row: {
                    "created_at": string,"email": string
                  }
                  Insert: {
                    "created_at"?: string,"email": string
                  }
                  Update: {
                    "created_at"?: string,"email"?: string
                  }
                  Relationships: [
                    
                  ]
                },"apps": {
                  Row: {
                    "created_at": string,"id": string,"key": string,"name": string,"support_mailbox": string | null
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"key": string,"name": string,"support_mailbox"?: string | null
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"key"?: string,"name"?: string,"support_mailbox"?: string | null
                  }
                  Relationships: [
                    
                  ]
                },"autonomy_modes": {
                  Row: {
                    "app_id": string,"case_type": string,"changed_at": string,"mode": string
                  }
                  Insert: {
                    "app_id": string,"case_type": string,"changed_at"?: string,"mode"?: string
                  }
                  Update: {
                    "app_id"?: string,"case_type"?: string,"changed_at"?: string,"mode"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "autonomy_modes_app_id_fkey"
      columns: ["app_id"]
isOneToOne: false
      referencedRelation: "apps"
      referencedColumns: ["id"]
    }
                  ]
                },"cancellation_reasons": {
                  Row: {
                    "created_at": string,"customer_email": string,"id": string,"stripe_customer_id": string | null,"stripe_feedback": string | null,"stripe_subscription_id": string | null,"ticket_id": string | null,"verbatim_reason": string
                  }
                  Insert: {
                    "created_at"?: string,"customer_email": string,"id"?: string,"stripe_customer_id"?: string | null,"stripe_feedback"?: string | null,"stripe_subscription_id"?: string | null,"ticket_id"?: string | null,"verbatim_reason": string
                  }
                  Update: {
                    "created_at"?: string,"customer_email"?: string,"id"?: string,"stripe_customer_id"?: string | null,"stripe_feedback"?: string | null,"stripe_subscription_id"?: string | null,"ticket_id"?: string | null,"verbatim_reason"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "cancellation_reasons_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"decisions": {
                  Row: {
                    "action_changes": Json | null,"created_at": string,"decided_at": string,"decision": string,"id": string,"note": string | null,"proposal_id": string | null,"reject_reason": string | null,"reply_diff": Json | null,"ticket_id": string,"time_to_decide_ms": number | null
                  }
                  Insert: {
                    "action_changes"?: Json | null,"created_at"?: string,"decided_at"?: string,"decision": string,"id"?: string,"note"?: string | null,"proposal_id"?: string | null,"reject_reason"?: string | null,"reply_diff"?: Json | null,"ticket_id": string,"time_to_decide_ms"?: number | null
                  }
                  Update: {
                    "action_changes"?: Json | null,"created_at"?: string,"decided_at"?: string,"decision"?: string,"id"?: string,"note"?: string | null,"proposal_id"?: string | null,"reject_reason"?: string | null,"reply_diff"?: Json | null,"ticket_id"?: string,"time_to_decide_ms"?: number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "decisions_proposal_id_fkey"
      columns: ["proposal_id"]
isOneToOne: false
      referencedRelation: "proposals"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "decisions_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"job_heartbeats": {
                  Row: {
                    "consecutive_failures": number,"created_at": string,"interval_seconds": number | null,"job": string,"last_alert_at": string | null,"last_error": string | null,"last_failed_at": string | null,"last_scheduled_at": string | null,"last_slot": string | null,"last_started_at": string | null,"last_succeeded_at": string | null,"updated_at": string
                  }
                  Insert: {
                    "consecutive_failures"?: number,"created_at"?: string,"interval_seconds"?: number | null,"job": string,"last_alert_at"?: string | null,"last_error"?: string | null,"last_failed_at"?: string | null,"last_scheduled_at"?: string | null,"last_slot"?: string | null,"last_started_at"?: string | null,"last_succeeded_at"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "consecutive_failures"?: number,"created_at"?: string,"interval_seconds"?: number | null,"job"?: string,"last_alert_at"?: string | null,"last_error"?: string | null,"last_failed_at"?: string | null,"last_scheduled_at"?: string | null,"last_slot"?: string | null,"last_started_at"?: string | null,"last_succeeded_at"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"job_runs": {
                  Row: {
                    "attempt": number,"created_at": string,"duration_ms": number | null,"error": string | null,"finished_at": string | null,"id": string,"job_id": string,"started_at": string,"status": string,"worker": string | null
                  }
                  Insert: {
                    "attempt": number,"created_at"?: string,"duration_ms"?: number | null,"error"?: string | null,"finished_at"?: string | null,"id"?: string,"job_id": string,"started_at"?: string,"status"?: string,"worker"?: string | null
                  }
                  Update: {
                    "attempt"?: number,"created_at"?: string,"duration_ms"?: number | null,"error"?: string | null,"finished_at"?: string | null,"id"?: string,"job_id"?: string,"started_at"?: string,"status"?: string,"worker"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "job_runs_job_id_fkey"
      columns: ["job_id"]
isOneToOne: false
      referencedRelation: "jobs"
      referencedColumns: ["id"]
    }
                  ]
                },"jobs": {
                  Row: {
                    "attempts": number,"created_at": string,"dedupe_key": string | null,"finished_at": string | null,"id": string,"last_error": string | null,"lock_ttl_seconds": number,"locked_at": string | null,"locked_by": string | null,"max_attempts": number,"payload": NonNullable<Json>,"run_at": string,"status": string,"type": string,"updated_at": string
                  }
                  Insert: {
                    "attempts"?: number,"created_at"?: string,"dedupe_key"?: string | null,"finished_at"?: string | null,"id"?: string,"last_error"?: string | null,"lock_ttl_seconds"?: number,"locked_at"?: string | null,"locked_by"?: string | null,"max_attempts"?: number,"payload"?: NonNullable<Json>,"run_at"?: string,"status"?: string,"type": string,"updated_at"?: string
                  }
                  Update: {
                    "attempts"?: number,"created_at"?: string,"dedupe_key"?: string | null,"finished_at"?: string | null,"id"?: string,"last_error"?: string | null,"lock_ttl_seconds"?: number,"locked_at"?: string | null,"locked_by"?: string | null,"max_attempts"?: number,"payload"?: NonNullable<Json>,"run_at"?: string,"status"?: string,"type"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"learning_events": {
                  Row: {
                    "created_at": string,"created_by": string | null,"id": string,"kind": string,"notion_page_id": string,"notion_url": string,"ticket_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by"?: string | null,"id"?: string,"kind": string,"notion_page_id": string,"notion_url": string,"ticket_id": string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string | null,"id"?: string,"kind"?: string,"notion_page_id"?: string,"notion_url"?: string,"ticket_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "learning_events_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"mail_backfills": {
                  Row: {
                    "created_at": string,"failed": number,"finished_at": string | null,"folder": string,"ignored": number,"imported": number,"last_error": string | null,"last_uid": number | null,"listed": number,"mailbox": string,"max_uid": number | null,"skipped": number,"started_at": string | null,"status": string,"tickets_created": number,"uid_validity": string | null,"updated_at": string
                  }
                  Insert: {
                    "created_at"?: string,"failed"?: number,"finished_at"?: string | null,"folder": string,"ignored"?: number,"imported"?: number,"last_error"?: string | null,"last_uid"?: number | null,"listed"?: number,"mailbox": string,"max_uid"?: number | null,"skipped"?: number,"started_at"?: string | null,"status"?: string,"tickets_created"?: number,"uid_validity"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"failed"?: number,"finished_at"?: string | null,"folder"?: string,"ignored"?: number,"imported"?: number,"last_error"?: string | null,"last_uid"?: number | null,"listed"?: number,"mailbox"?: string,"max_uid"?: number | null,"skipped"?: number,"started_at"?: string | null,"status"?: string,"tickets_created"?: number,"uid_validity"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"mail_cursors": {
                  Row: {
                    "cursor": string | null,"cursor_meta": NonNullable<Json>,"last_fetch_at": string | null,"last_result": Json | null,"mailbox": string,"provider": string,"updated_at": string
                  }
                  Insert: {
                    "cursor"?: string | null,"cursor_meta"?: NonNullable<Json>,"last_fetch_at"?: string | null,"last_result"?: Json | null,"mailbox": string,"provider": string,"updated_at"?: string
                  }
                  Update: {
                    "cursor"?: string | null,"cursor_meta"?: NonNullable<Json>,"last_fetch_at"?: string | null,"last_result"?: Json | null,"mailbox"?: string,"provider"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"mail_ignored": {
                  Row: {
                    "created_at": string,"from_email": string | null,"id": string,"message_id": string | null,"provider_message_id": string | null,"reason": string,"received_at": string | null,"subject": string | null
                  }
                  Insert: {
                    "created_at"?: string,"from_email"?: string | null,"id"?: string,"message_id"?: string | null,"provider_message_id"?: string | null,"reason": string,"received_at"?: string | null,"subject"?: string | null
                  }
                  Update: {
                    "created_at"?: string,"from_email"?: string | null,"id"?: string,"message_id"?: string | null,"provider_message_id"?: string | null,"reason"?: string,"received_at"?: string | null,"subject"?: string | null
                  }
                  Relationships: [
                    
                  ]
                },"mail_sends": {
                  Row: {
                    "attempts": number,"created_at": string,"idempotency_key": string,"kind": string,"last_error": string | null,"message_row_id": string | null,"provider_message_id": string | null,"rfc_message_id": string,"sent_at": string | null,"started_at": string,"status": string,"subject": string | null,"ticket_id": string | null,"to_emails": (string)[],"updated_at": string
                  }
                  Insert: {
                    "attempts"?: number,"created_at"?: string,"idempotency_key": string,"kind": string,"last_error"?: string | null,"message_row_id"?: string | null,"provider_message_id"?: string | null,"rfc_message_id": string,"sent_at"?: string | null,"started_at"?: string,"status"?: string,"subject"?: string | null,"ticket_id"?: string | null,"to_emails"?: (string)[],"updated_at"?: string
                  }
                  Update: {
                    "attempts"?: number,"created_at"?: string,"idempotency_key"?: string,"kind"?: string,"last_error"?: string | null,"message_row_id"?: string | null,"provider_message_id"?: string | null,"rfc_message_id"?: string,"sent_at"?: string | null,"started_at"?: string,"status"?: string,"subject"?: string | null,"ticket_id"?: string | null,"to_emails"?: (string)[],"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "mail_sends_message_row_id_fkey"
      columns: ["message_row_id"]
isOneToOne: false
      referencedRelation: "messages"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "mail_sends_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"messages": {
                  Row: {
                    "attachments": NonNullable<Json>,"cc_emails": (string)[],"created_at": string,"direction": string,"from_email": string,"from_name": string | null,"headers": NonNullable<Json>,"html_body": string | null,"id": string,"in_reply_to": string | null,"message_id": string | null,"provider_message_id": string | null,"provider_thread_id": string | null,"raw_storage_path": string | null,"received_at": string | null,"references": (string)[],"sent_at": string | null,"sent_by": string | null,"subject": string | null,"text_body": string | null,"text_stripped": string | null,"ticket_id": string,"to_emails": (string)[],"translation": string | null
                  }
                  Insert: {
                    "attachments"?: NonNullable<Json>,"cc_emails"?: (string)[],"created_at"?: string,"direction": string,"from_email": string,"from_name"?: string | null,"headers"?: NonNullable<Json>,"html_body"?: string | null,"id"?: string,"in_reply_to"?: string | null,"message_id"?: string | null,"provider_message_id"?: string | null,"provider_thread_id"?: string | null,"raw_storage_path"?: string | null,"received_at"?: string | null,"references"?: (string)[],"sent_at"?: string | null,"sent_by"?: string | null,"subject"?: string | null,"text_body"?: string | null,"text_stripped"?: string | null,"ticket_id": string,"to_emails"?: (string)[],"translation"?: string | null
                  }
                  Update: {
                    "attachments"?: NonNullable<Json>,"cc_emails"?: (string)[],"created_at"?: string,"direction"?: string,"from_email"?: string,"from_name"?: string | null,"headers"?: NonNullable<Json>,"html_body"?: string | null,"id"?: string,"in_reply_to"?: string | null,"message_id"?: string | null,"provider_message_id"?: string | null,"provider_thread_id"?: string | null,"raw_storage_path"?: string | null,"received_at"?: string | null,"references"?: (string)[],"sent_at"?: string | null,"sent_by"?: string | null,"subject"?: string | null,"text_body"?: string | null,"text_stripped"?: string | null,"ticket_id"?: string,"to_emails"?: (string)[],"translation"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "messages_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"model_calls": {
                  Row: {
                    "attempt": number | null,"cache_creation_tokens": number,"cache_read_tokens": number,"cost_usd": number | null,"created_at": string,"duration_ms": number | null,"error": string | null,"id": string,"input_tokens": number,"model": string,"output_tokens": number,"purpose": string,"run_id": string | null,"status": string,"stop_reason": string | null,"ticket_id": string | null,"turn": number | null
                  }
                  Insert: {
                    "attempt"?: number | null,"cache_creation_tokens"?: number,"cache_read_tokens"?: number,"cost_usd"?: number | null,"created_at"?: string,"duration_ms"?: number | null,"error"?: string | null,"id"?: string,"input_tokens"?: number,"model": string,"output_tokens"?: number,"purpose": string,"run_id"?: string | null,"status"?: string,"stop_reason"?: string | null,"ticket_id"?: string | null,"turn"?: number | null
                  }
                  Update: {
                    "attempt"?: number | null,"cache_creation_tokens"?: number,"cache_read_tokens"?: number,"cost_usd"?: number | null,"created_at"?: string,"duration_ms"?: number | null,"error"?: string | null,"id"?: string,"input_tokens"?: number,"model"?: string,"output_tokens"?: number,"purpose"?: string,"run_id"?: string | null,"status"?: string,"stop_reason"?: string | null,"ticket_id"?: string | null,"turn"?: number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "model_calls_run_id_fkey"
      columns: ["run_id"]
isOneToOne: false
      referencedRelation: "agent_runs"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "model_calls_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"notifications": {
                  Row: {
                    "app_id": string | null,"body": string,"created_at": string,"dedupe_key": string | null,"error": string | null,"id": string,"kind": string,"meta": NonNullable<Json>,"recipient": string | null,"sent_at": string | null,"status": string,"subject": string,"ticket_id": string | null
                  }
                  Insert: {
                    "app_id"?: string | null,"body"?: string,"created_at"?: string,"dedupe_key"?: string | null,"error"?: string | null,"id"?: string,"kind": string,"meta"?: NonNullable<Json>,"recipient"?: string | null,"sent_at"?: string | null,"status"?: string,"subject"?: string,"ticket_id"?: string | null
                  }
                  Update: {
                    "app_id"?: string | null,"body"?: string,"created_at"?: string,"dedupe_key"?: string | null,"error"?: string | null,"id"?: string,"kind"?: string,"meta"?: NonNullable<Json>,"recipient"?: string | null,"sent_at"?: string | null,"status"?: string,"subject"?: string,"ticket_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "notifications_app_id_fkey"
      columns: ["app_id"]
isOneToOne: false
      referencedRelation: "apps"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "notifications_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"proposals": {
                  Row: {
                    "candidate_cases": NonNullable<Json>,"case_type": string,"conclusion": string | null,"confidence": number | null,"created_at": string,"customer_confirmation_needed": boolean,"due_date": string | null,"id": string,"knowledge_refs": NonNullable<Json>,"meta_line": string | null,"no_knowledge_found": boolean,"policy_warnings": (string)[],"reply_draft": Json | null,"research": NonNullable<Json>,"research_warnings": (string)[],"risk_level": string,"risk_reason": string | null,"run_id": string | null,"stage": number,"status": string,"summary_line": string,"ticket_id": string,"version": number
                  }
                  Insert: {
                    "candidate_cases"?: NonNullable<Json>,"case_type": string,"conclusion"?: string | null,"confidence"?: number | null,"created_at"?: string,"customer_confirmation_needed"?: boolean,"due_date"?: string | null,"id"?: string,"knowledge_refs"?: NonNullable<Json>,"meta_line"?: string | null,"no_knowledge_found"?: boolean,"policy_warnings"?: (string)[],"reply_draft"?: Json | null,"research"?: NonNullable<Json>,"research_warnings"?: (string)[],"risk_level"?: string,"risk_reason"?: string | null,"run_id"?: string | null,"stage"?: number,"status"?: string,"summary_line": string,"ticket_id": string,"version": number
                  }
                  Update: {
                    "candidate_cases"?: NonNullable<Json>,"case_type"?: string,"conclusion"?: string | null,"confidence"?: number | null,"created_at"?: string,"customer_confirmation_needed"?: boolean,"due_date"?: string | null,"id"?: string,"knowledge_refs"?: NonNullable<Json>,"meta_line"?: string | null,"no_knowledge_found"?: boolean,"policy_warnings"?: (string)[],"reply_draft"?: Json | null,"research"?: NonNullable<Json>,"research_warnings"?: (string)[],"risk_level"?: string,"risk_reason"?: string | null,"run_id"?: string | null,"stage"?: number,"status"?: string,"summary_line"?: string,"ticket_id"?: string,"version"?: number
                  }
                  Relationships: [
                    {
      foreignKeyName: "proposals_run_id_fkey"
      columns: ["run_id"]
isOneToOne: false
      referencedRelation: "agent_runs"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "proposals_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"proposed_actions": {
                  Row: {
                    "action_type": string,"created_at": string,"enabled": boolean,"id": string,"params": NonNullable<Json>,"position": number,"proposal_id": string,"reason": string,"required_for_reply": boolean,"stage": string
                  }
                  Insert: {
                    "action_type": string,"created_at"?: string,"enabled"?: boolean,"id"?: string,"params"?: NonNullable<Json>,"position": number,"proposal_id": string,"reason"?: string,"required_for_reply"?: boolean,"stage"?: string
                  }
                  Update: {
                    "action_type"?: string,"created_at"?: string,"enabled"?: boolean,"id"?: string,"params"?: NonNullable<Json>,"position"?: number,"proposal_id"?: string,"reason"?: string,"required_for_reply"?: boolean,"stage"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "proposed_actions_proposal_id_fkey"
      columns: ["proposal_id"]
isOneToOne: false
      referencedRelation: "proposals"
      referencedColumns: ["id"]
    }
                  ]
                },"release_notifications": {
                  Row: {
                    "app_id": string,"created_at": string,"email": string,"id": string,"linear_issue_id": string | null,"linear_issue_identifier": string,"notification_ticket_id": string | null,"notified_at": string | null,"ticket_id": string | null
                  }
                  Insert: {
                    "app_id": string,"created_at"?: string,"email": string,"id"?: string,"linear_issue_id"?: string | null,"linear_issue_identifier": string,"notification_ticket_id"?: string | null,"notified_at"?: string | null,"ticket_id"?: string | null
                  }
                  Update: {
                    "app_id"?: string,"created_at"?: string,"email"?: string,"id"?: string,"linear_issue_id"?: string | null,"linear_issue_identifier"?: string,"notification_ticket_id"?: string | null,"notified_at"?: string | null,"ticket_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "release_notifications_app_id_fkey"
      columns: ["app_id"]
isOneToOne: false
      referencedRelation: "apps"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "release_notifications_notification_ticket_id_fkey"
      columns: ["notification_ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "release_notifications_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"settings": {
                  Row: {
                    "app_id": string,"auto_close_days": number,"digest_time": string,"follow_up_days": number,"global_pause": boolean,"notify_email": string | null,"refund_daily_limit_amount_cents": number,"refund_daily_limit_count": number,"timezone": string,"undo_window_minutes": number,"updated_at": string
                  }
                  Insert: {
                    "app_id": string,"auto_close_days"?: number,"digest_time"?: string,"follow_up_days"?: number,"global_pause"?: boolean,"notify_email"?: string | null,"refund_daily_limit_amount_cents"?: number,"refund_daily_limit_count"?: number,"timezone"?: string,"undo_window_minutes"?: number,"updated_at"?: string
                  }
                  Update: {
                    "app_id"?: string,"auto_close_days"?: number,"digest_time"?: string,"follow_up_days"?: number,"global_pause"?: boolean,"notify_email"?: string | null,"refund_daily_limit_amount_cents"?: number,"refund_daily_limit_count"?: number,"timezone"?: string,"undo_window_minutes"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "settings_app_id_fkey"
      columns: ["app_id"]
isOneToOne: true
      referencedRelation: "apps"
      referencedColumns: ["id"]
    }
                  ]
                },"settings_audit": {
                  Row: {
                    "app_id": string,"changed_by": string,"created_at": string,"id": string,"key": string,"new_value": Json | null,"old_value": Json | null,"scope": string,"summary": string
                  }
                  Insert: {
                    "app_id": string,"changed_by": string,"created_at"?: string,"id"?: string,"key": string,"new_value"?: Json | null,"old_value"?: Json | null,"scope": string,"summary"?: string
                  }
                  Update: {
                    "app_id"?: string,"changed_by"?: string,"created_at"?: string,"id"?: string,"key"?: string,"new_value"?: Json | null,"old_value"?: Json | null,"scope"?: string,"summary"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "settings_audit_app_id_fkey"
      columns: ["app_id"]
isOneToOne: false
      referencedRelation: "apps"
      referencedColumns: ["id"]
    }
                  ]
                },"ticket_classifications": {
                  Row: {
                    "attempts": number,"case_type": string | null,"confidence": number | null,"created_at": string,"last_error": string | null,"model": string | null,"rationale": string | null,"ticket_id": string,"updated_at": string
                  }
                  Insert: {
                    "attempts"?: number,"case_type"?: string | null,"confidence"?: number | null,"created_at"?: string,"last_error"?: string | null,"model"?: string | null,"rationale"?: string | null,"ticket_id": string,"updated_at"?: string
                  }
                  Update: {
                    "attempts"?: number,"case_type"?: string | null,"confidence"?: number | null,"created_at"?: string,"last_error"?: string | null,"model"?: string | null,"rationale"?: string | null,"ticket_id"?: string,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ticket_classifications_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: true
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"ticket_follow_ups": {
                  Row: {
                    "created_at": string,"id": string,"job_id": string | null,"kind": string,"ticket_id": string,"waiting_since": string
                  }
                  Insert: {
                    "created_at"?: string,"id"?: string,"job_id"?: string | null,"kind": string,"ticket_id": string,"waiting_since": string
                  }
                  Update: {
                    "created_at"?: string,"id"?: string,"job_id"?: string | null,"kind"?: string,"ticket_id"?: string,"waiting_since"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ticket_follow_ups_job_id_fkey"
      columns: ["job_id"]
isOneToOne: false
      referencedRelation: "jobs"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "ticket_follow_ups_ticket_id_fkey"
      columns: ["ticket_id"]
isOneToOne: false
      referencedRelation: "tickets"
      referencedColumns: ["id"]
    }
                  ]
                },"tickets": {
                  Row: {
                    "app_id": string,"case_confidence": number | null,"case_type": string | null,"closed_at": string | null,"created_at": string,"customer_context": Json | null,"customer_email": string,"customer_name": string | null,"display_number": number,"due_date": string | null,"first_message_at": string | null,"id": string,"imported_at": string | null,"instaradar_user_id": string | null,"last_customer_message_at": string | null,"last_message_at": string | null,"resolution": string | null,"risk_level": string,"risk_reason": string | null,"snoozed_until": string | null,"stage": number,"status": string,"stripe_customer_id": string | null,"subject": string | null,"tags": (string)[],"updated_at": string,"waiting_for": string | null
                  }
                  Insert: {
                    "app_id": string,"case_confidence"?: number | null,"case_type"?: string | null,"closed_at"?: string | null,"created_at"?: string,"customer_context"?: Json | null,"customer_email": string,"customer_name"?: string | null,"display_number"?: number,"due_date"?: string | null,"first_message_at"?: string | null,"id"?: string,"imported_at"?: string | null,"instaradar_user_id"?: string | null,"last_customer_message_at"?: string | null,"last_message_at"?: string | null,"resolution"?: string | null,"risk_level"?: string,"risk_reason"?: string | null,"snoozed_until"?: string | null,"stage"?: number,"status"?: string,"stripe_customer_id"?: string | null,"subject"?: string | null,"tags"?: (string)[],"updated_at"?: string,"waiting_for"?: string | null
                  }
                  Update: {
                    "app_id"?: string,"case_confidence"?: number | null,"case_type"?: string | null,"closed_at"?: string | null,"created_at"?: string,"customer_context"?: Json | null,"customer_email"?: string,"customer_name"?: string | null,"display_number"?: number,"due_date"?: string | null,"first_message_at"?: string | null,"id"?: string,"imported_at"?: string | null,"instaradar_user_id"?: string | null,"last_customer_message_at"?: string | null,"last_message_at"?: string | null,"resolution"?: string | null,"risk_level"?: string,"risk_reason"?: string | null,"snoozed_until"?: string | null,"stage"?: number,"status"?: string,"stripe_customer_id"?: string | null,"subject"?: string | null,"tags"?: (string)[],"updated_at"?: string,"waiting_for"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "tickets_app_id_fkey"
      columns: ["app_id"]
isOneToOne: false
      referencedRelation: "apps"
      referencedColumns: ["id"]
    }
                  ]
                },"vercel_logs": {
                  Row: {
                    "at": string,"created_at": string,"deployment_id": string | null,"id": number,"level": string,"message": string,"raw": Json | null,"request_id": string | null,"source": string | null
                  }
                  Insert: {
                    "at": string,"created_at"?: string,"deployment_id"?: string | null,"id"?: never,"level"?: string,"message": string,"raw"?: Json | null,"request_id"?: string | null,"source"?: string | null
                  }
                  Update: {
                    "at"?: string,"created_at"?: string,"deployment_id"?: string | null,"id"?: never,"level"?: string,"message"?: string,"raw"?: Json | null,"request_id"?: string | null,"source"?: string | null
                  }
                  Relationships: [
                    
                  ]
                }
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            "dearmor":
{ Args: { "": string }; Returns: string
                           },
"gen_random_uuid":
{ Args: Record<PropertyKey, never>; Returns: string
                           },
"gen_salt":
{ Args: { "": string }; Returns: string
                           },
"is_allowed_user":
{ Args: Record<PropertyKey, never>; Returns: boolean
                           },
"pgp_armor_headers":
{ Args: { "": string }; Returns: Record<string, unknown>[]
                           }
          }
          Enums: {
            [_ in never]: never
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            
          }
        }
} as const

