/**
 * pnpm db:types
 * Generates shared/types/database.ts from SUPABASE_DB_URL with the Supabase CLI
 * (`supabase gen types typescript --db-url …`). Run after every migration change.
 */
import { spawnSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { ROOT, requireDbUrl } from './lib/db'

const rawUrl = requireDbUrl()
// Local clusters usually have no TLS; the CLI insists on it unless told otherwise.
const url = /sslmode=/.test(rawUrl)
  ? rawUrl
  : rawUrl + (rawUrl.includes('?') ? '&' : '?') + 'sslmode=disable'
const out = path.join(ROOT, 'shared', 'types', 'database.ts')
const r = spawnSync(
  'pnpm',
  ['exec', 'supabase', 'gen', 'types', 'typescript', '--db-url', url, '--schema', 'public'],
  {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  },
)
if (r.status !== 0) {
  console.error(r.stderr || r.stdout)
  process.exit(r.status ?? 1)
}
const header = `// Generated by \`pnpm db:types\` from the Supabase schema. Do not edit by hand.\n// eslint-disable\n`
writeFileSync(out, header + r.stdout)
console.log(`wrote ${path.relative(ROOT, out)}`)
