-- Maelle foundation schema (IRDR-454).
-- Table names are binding. Other tickets add columns and tables in their own migrations, additive only.
-- Status-like columns are text with CHECK constraints (not enums) so later migrations can extend them
-- with a single `alter table … drop constraint / add constraint`.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- auth allow-list

create table if not exists public.allowed_users (
  email text primary key check (email = lower(email)),
  created_at timestamptz not null default now()
);

comment on table public.allowed_users is 'The only emails that may sign in. Filled from ALLOWED_USER_EMAIL by pnpm db:migrate.';

create or replace function public.is_allowed_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.allowed_users a
    where a.email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_allowed_user() from public;
grant execute on function public.is_allowed_user() to authenticated, anon, service_role;

-- Reject any sign-up that is not on the allow-list, before the auth row exists.
create or replace function public.enforce_allowed_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.email is null or not exists (
    select 1 from public.allowed_users a where a.email = lower(new.email)
  ) then
    raise exception 'Sign-in is not allowed for this email' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_allowed_user on auth.users;
create trigger enforce_allowed_user
  before insert on auth.users
  for each row execute function public.enforce_allowed_user();

-- ---------------------------------------------------------------- helpers

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------- apps

create table if not exists public.apps (
  id uuid primary key default gen_random_uuid(),
  key text not null unique,
  name text not null,
  support_mailbox text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- tickets

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  app_id uuid not null references public.apps(id) on delete restrict,
  display_number integer generated by default as identity (start with 4801),
  customer_email text not null,
  customer_name text,
  subject text,
  status text not null default 'new'
    check (status in ('new','researching','needs_decision','executing','closed','action_failed','waiting_on_customer','snoozed','manual','auto_pending')),
  resolution text
    check (resolution is null or resolution in ('approved','approved_with_edits','rejected','handled_manually','auto','marked_done','closed_no_reply')),
  case_type text,
  case_confidence real check (case_confidence is null or (case_confidence >= 0 and case_confidence <= 1)),
  risk_level text not null default 'none' check (risk_level in ('none','high','safety')),
  risk_reason text,
  due_date date,
  stage smallint not null default 1 check (stage in (1, 2)),
  waiting_for text,
  snoozed_until timestamptz,
  tags text[] not null default '{}',
  instaradar_user_id text,
  stripe_customer_id text,
  customer_context jsonb,
  first_message_at timestamptz,
  last_message_at timestamptz,
  last_customer_message_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (app_id, display_number)
);

create index if not exists tickets_status_idx on public.tickets (app_id, status);
create index if not exists tickets_customer_email_idx on public.tickets (lower(customer_email));
create index if not exists tickets_closed_at_idx on public.tickets (closed_at desc) where status = 'closed';
create index if not exists tickets_snoozed_until_idx on public.tickets (snoozed_until) where status = 'snoozed';

create trigger tickets_set_updated_at before update on public.tickets
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- messages

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  direction text not null check (direction in ('in','out')),
  provider_message_id text,
  message_id text,
  in_reply_to text,
  "references" text[] not null default '{}',
  from_email text not null,
  from_name text,
  to_emails text[] not null default '{}',
  cc_emails text[] not null default '{}',
  subject text,
  text_body text,
  html_body text,
  translation text,
  attachments jsonb not null default '[]'::jsonb,
  raw_storage_path text,
  received_at timestamptz,
  sent_at timestamptz,
  sent_by text check (sent_by is null or sent_by in ('you','auto')),
  created_at timestamptz not null default now()
);

create index if not exists messages_ticket_idx on public.messages (ticket_id, created_at);
create unique index if not exists messages_provider_message_id_key on public.messages (provider_message_id) where provider_message_id is not null;
create unique index if not exists messages_message_id_key on public.messages (message_id) where message_id is not null;

-- ---------------------------------------------------------------- agent_runs

create table if not exists public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  trigger text not null check (trigger in ('new_ticket','customer_reply','case_override','follow_up','release_notification','rerun')),
  status text not null default 'queued' check (status in ('queued','running','succeeded','failed','cancelled')),
  -- per source: stripe, supabase, vercel, kb, linear, email → pending | ok | failed | skipped
  progress jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  finished_at timestamptz,
  duration_ms integer,
  model text,
  input_tokens integer,
  output_tokens integer,
  error text,
  proposal_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists agent_runs_ticket_idx on public.agent_runs (ticket_id, created_at desc);

-- ---------------------------------------------------------------- proposals

create table if not exists public.proposals (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  run_id uuid references public.agent_runs(id) on delete set null,
  version integer not null,
  case_type text not null,
  confidence real,
  candidate_cases jsonb not null default '[]'::jsonb,
  summary_line text not null,
  meta_line text,
  risk_level text not null default 'none' check (risk_level in ('none','high','safety')),
  risk_reason text,
  due_date date,
  customer_confirmation_needed boolean not null default false,
  stage smallint not null default 1 check (stage in (1, 2)),
  research jsonb not null default '[]'::jsonb,
  research_warnings text[] not null default '{}',
  policy_warnings text[] not null default '{}',
  conclusion text,
  -- { template, templateNotionPageId, to, subject, body, attachments: [{ name, storagePath, contentType, sizeBytes }] }
  reply_draft jsonb,
  knowledge_refs jsonb not null default '[]'::jsonb,
  no_knowledge_found boolean not null default false,
  status text not null default 'active' check (status in ('active','superseded','decided')),
  created_at timestamptz not null default now(),
  unique (ticket_id, version)
);

create index if not exists proposals_ticket_active_idx on public.proposals (ticket_id) where status = 'active';

alter table public.agent_runs
  drop constraint if exists agent_runs_proposal_id_fkey,
  add constraint agent_runs_proposal_id_fkey foreign key (proposal_id) references public.proposals(id) on delete set null;

-- ---------------------------------------------------------------- proposed_actions

create table if not exists public.proposed_actions (
  id uuid primary key default gen_random_uuid(),
  proposal_id uuid not null references public.proposals(id) on delete cascade,
  position integer not null,
  action_type text not null,
  params jsonb not null default '{}'::jsonb,
  reason text not null default '',
  stage text not null default 'now' check (stage in ('now','after_confirmation')),
  required_for_reply boolean not null default false,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique (proposal_id, position)
);

-- ---------------------------------------------------------------- action_executions (the audit log)

create table if not exists public.action_executions (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  proposal_id uuid references public.proposals(id) on delete set null,
  proposed_action_id uuid references public.proposed_actions(id) on delete set null,
  action_type text not null,
  params jsonb not null default '{}'::jsonb,
  executed_by text not null check (executed_by in ('you','auto')),
  status text not null default 'queued' check (status in ('queued','scheduled','running','succeeded','failed','held','cancelled')),
  -- undo window for Auto replies
  scheduled_for timestamptz,
  idempotency_key text not null,
  attempt integer not null default 1,
  result jsonb,
  error text,
  -- Stripe / Linear ids, request ids
  external_refs jsonb not null default '{}'::jsonb,
  irreversible boolean not null default false,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (idempotency_key)
);

create index if not exists action_executions_ticket_idx on public.action_executions (ticket_id, created_at);
create index if not exists action_executions_created_idx on public.action_executions (created_at desc);
create index if not exists action_executions_scheduled_idx on public.action_executions (scheduled_for) where status = 'scheduled';

create trigger action_executions_set_updated_at before update on public.action_executions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- decisions

create table if not exists public.decisions (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  proposal_id uuid references public.proposals(id) on delete set null,
  decision text not null check (decision in ('approved','approved_with_edits','rejected','handled_manually','snoozed','marked_done','auto')),
  reject_reason text check (reject_reason is null or reject_reason in ('wrong_case','wrong_actions','wrong_tone','handle_myself')),
  note text,
  reply_diff jsonb,
  action_changes jsonb,
  time_to_decide_ms integer,
  decided_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists decisions_ticket_idx on public.decisions (ticket_id, decided_at desc);
create index if not exists decisions_decided_at_idx on public.decisions (decided_at desc);

-- ---------------------------------------------------------------- release_notifications

create table if not exists public.release_notifications (
  id uuid primary key default gen_random_uuid(),
  app_id uuid not null references public.apps(id) on delete restrict,
  linear_issue_id text,
  linear_issue_identifier text not null,
  email text not null,
  ticket_id uuid references public.tickets(id) on delete set null,
  notified_at timestamptz,
  notification_ticket_id uuid references public.tickets(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (linear_issue_identifier, email)
);

-- ---------------------------------------------------------------- cancellation_reasons

create table if not exists public.cancellation_reasons (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid references public.tickets(id) on delete set null,
  customer_email text not null,
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_feedback text check (stripe_feedback is null or stripe_feedback in ('customer_service','low_quality','missing_features','other','switched_service','too_complex','too_expensive','unused')),
  verbatim_reason text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------- settings (one row per app)

create table if not exists public.settings (
  app_id uuid primary key references public.apps(id) on delete cascade,
  global_pause boolean not null default false,
  undo_window_minutes smallint not null default 10 check (undo_window_minutes in (5, 10, 15)),
  digest_time time not null default '08:00',
  timezone text not null default 'Europe/Berlin',
  follow_up_days smallint not null default 3 check (follow_up_days > 0),
  auto_close_days smallint not null default 7 check (auto_close_days > 0),
  refund_daily_limit_count integer not null default 3 check (refund_daily_limit_count >= 0),
  refund_daily_limit_amount_cents integer not null default 10000 check (refund_daily_limit_amount_cents >= 0),
  notify_email text,
  updated_at timestamptz not null default now()
);

create trigger settings_set_updated_at before update on public.settings
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- autonomy_modes, action_locks

create table if not exists public.autonomy_modes (
  app_id uuid not null references public.apps(id) on delete cascade,
  case_type text not null,
  mode text not null default 'always_ask' check (mode in ('always_ask','auto')),
  changed_at timestamptz not null default now(),
  primary key (app_id, case_type)
);

create table if not exists public.action_locks (
  app_id uuid not null references public.apps(id) on delete cascade,
  action_type text not null,
  locked boolean not null default false,
  changed_at timestamptz not null default now(),
  primary key (app_id, action_type)
);

-- ---------------------------------------------------------------- RLS: only the allowed user (service role bypasses)

do $$
declare
  t text;
begin
  foreach t in array array[
    'allowed_users','apps','tickets','messages','agent_runs','proposals','proposed_actions',
    'action_executions','decisions','release_notifications','cancellation_reasons','settings',
    'autonomy_modes','action_locks'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists allowed_user_all on public.%I', t);
    execute format(
      'create policy allowed_user_all on public.%I for all to authenticated using (public.is_allowed_user()) with check (public.is_allowed_user())',
      t
    );
  end loop;
end $$;

-- ---------------------------------------------------------------- Realtime on tickets, agent_runs, action_executions

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tickets') then
      alter publication supabase_realtime add table public.tickets;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'agent_runs') then
      alter publication supabase_realtime add table public.agent_runs;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'action_executions') then
      alter publication supabase_realtime add table public.action_executions;
    end if;
  end if;
end $$;

-- ---------------------------------------------------------------- Storage bucket for attachments (Supabase only)

do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'storage' and table_name = 'buckets') then
    insert into storage.buckets (id, name, public)
    values ('attachments', 'attachments', false)
    on conflict (id) do nothing;
  end if;
end $$;
